[api]
enabled = true

[db]
port = 5432
shadow_port = 5433
major_version = 15

[studio]
enabled = true

[inbucket]
enabled = true

[auth]
enabled = true
site_url = "https://zaiko-portal.colegiogoyavier.edu.co/"
additional_redirect_urls = [
  "http://localhost:5500",
  "http://127.0.0.1:5500",
  "http://localhost:5500/?oauth_mode=topnav",
  "http://localhost:5500/",
  "https://zaiko-portal.colegiogoyavier.edu.co/",
  "https://zaiko-pazsalvo.colegiogoyavier.edu.co/",
]
password_requirements = "letters_digits"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = true
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[edge_runtime]
enabled = true

[functions.ps-api]
verify_jwt = true
